blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.post_list, name = 'post_list'),
	#url(r'^$', views.PostListView.as_view(), name='post_list'),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
	url(r'^(?P<post_id>\d+)/share/$', views.post_share, name = 'post_share'),
	url(r'^tag/(?P<tag_slug>[-\w]+)$', views.post_list, name = 'post_list_by_tag'),
	]

django_example/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
# Create your models here.

class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')
		
		
class Post(models.Model):
	STATUS_CHOICES = ( ('draft', 'Draft'), ('published', 'Published'),)
	title = models.CharField(max_length = 250)
	slug = models.SlugField(max_length=250, unique_for_date = 'publish')
	author = models.ForeignKey(User, related_name = 'blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default = timezone.now)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES,default='draft')
	objects = models.Manager()
	published = PublishedManager()
	tags = TaggableManager()
	
	class Meta:
		ordering = ('-publish',)
		
	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])
		
		
	def __str__(self):
		return self.title

#now lets try to create a custom manager.
#this manager will only show the query consisting of the posts which are published.

class Comment(models.Model):
	post = models.ForeignKey(Post, related_name = 'comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)
	active = models.BooleanField(default = True)
	
	class Meta:
		ordering = ('created',)
		
	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)


	

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length = 25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required = True, widget = forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'body')
#this is an example of a dynamically loaded form.

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
# Create your views here.
#in this view we retrieve the list of all the posts with the published status using our manager.

	
def post_detail(request, year, month, day, post):
    """
    """
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    #list of active comments for this post
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        #A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #Created Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return  render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})

	
"""
Steps : we instantiate the paginator class with the number of objects we want to display in each page
we get the page GET parameter that indicates the current page number
we obtain the objcts for the desired page by calling the page() method of the paginator.
if the page parameter is not an integer, we retrieve the first page of the results, if this parameter is a number greater than the last page of results, we retrieve the last page
we pass the page number and retrieved objects to the template
"""
def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None
	
	if tag_slug:
		tag = get_object_or_404(Tag, slug = tag_slug)
		object_list = object_list.filter(tags__in=[tag])
		
	paginator = Paginator(object_list, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)
	return render(request, 'blog/post/list.html', {'page':page, 'posts':posts, 'tag':tag})
	
def post_share(request, post_id):
	#retrieve post by id
	post = get_object_or_404(Post, id=post_id, status='published')
	sent = False
	
	if request.method == 'POST':
		#form was submitted
		form = EmailPostForm(request.POST)
		if form.is_valid():
			#form fields pased validation
			cd = form.cleaned_data
			#.... send the mail
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'admin@myblog.com',[cd['to']])
			sent = True
			
	else:
		form = EmailPostForm() #we create a new form instance that will be used to diaplay an empty form
	return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})
		
"""
Notes on using the form - we use the same view to display the intial form and process the submitted data. we differentiate the form was submitted or not based on the request method. we are going to submit the form usng the post method. we assume that if we get the get request, an empt form has to be diplayed, and if we get a post request, the form has been submitted and needs to be processed.
"""

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %} {% endblock %} </title>
<link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>

<div id="content">
{% block content %}
{% endblock %}
</div>

<div id="sidebar">
	<h2> Poonam's blog </h2>
	<p> This is my blog. </p>
</div>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number}}">Previous</a>
		{% endif %}
		<span class="current">
		Page {{page.number}} of {{page.paginator.num_pages}}. </span>
		{% if page.has_next %}
			<a href="?page={{page.next_page_number}}">Next</a>
		{% endif %}
	</span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}

    <p>
      <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {%  endif %}




{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title  %}My blog{% endblock %}
{% block content %}

  {% include "pagination.html" with page=posts %}

  <h1>My Blog</h1>

  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>

  {% endfor %}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number}}">Previous</a>
		{% endif %}
		<span class="current">
		Page {{page.number}} of {{page.paginator.num_pages}}. </span>
		{% if page.has_next %}
			<a href="?page={{page.next_page_number}}">Next</a>
		{% endif %}
	</span>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %} Share a post! {% endblock %}
{% block content %}
{% if sent %}
<h1> E-mail sent successfully. </h1>
<p> "{{ post.title }}" was sent successfully sent to {{cd.to}}. </p>
{% else %}
<h1> Share "{{post.title}}" by e-mail </h1>
<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}